{
 "title": "Healthcheck Overview 1.0",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "papiHost", "label": "Cluster", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "papiHost" },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "data": "{ \n\"name\" :  \"${papiHost:text}\"\n }",
     "source": "inline",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "OneFS Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "release", "text": "OneFS Version", "type": "string" }
     ],
     "root_selector": "$.onefs_version",
     "source": "url",
     "type": "json",
     "url": "https://${papiHost:value}:8080/platform/3/cluster/config",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.health",
     "query": "SELECT max(\"value\") FROM \"cluster.health\" WHERE (\"cluster\" =~ /${papiHost:text}/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$papiHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.node.count.down",
     "query": "SELECT mean(\"value\") FROM \"cluster.node.count.down\" WHERE (\"cluster\" =~ /${papiHost:text}/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Read-only Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster.node.count.readonly",
     "query": "SELECT mean(\"value\") FROM \"cluster.node.count.readonly\" WHERE (\"cluster\" =~ /${papiHost:text}/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Healthcheck Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "checklist_id", "text": "", "type": "string" },
      { "selector": "id", "text": "", "type": "string" },
      { "selector": "start_time", "text": "", "type": "timestamp_epoch_s" },
      { "selector": "run_status", "text": "", "type": "string" },
      { "selector": "result", "text": "", "type": "string" }
     ],
     "filters": [
      { "field": "", "operator": "contains", "value": [ "basic" ] }
     ],
     "source": "url",
     "type": "json",
     "url": "https://${papiHost}:8080/platform/10/healthcheck/evaluations",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "level", "value": "list" }
      ]
     }
    }
   ]
  }
 ]
}